#!/bin/bash
mkfifo -m 600 $XDG_RUNTIME_DIR/msg
~/Repo/romsom/scripts/notifications.py > $XDG_RUNTIME_DIR/msg &
firefox &
# spawn some terms
kitty --class 'term-main' &
kitty --class 'term-main' &
kitty --class 'term-main' &
kitty --class 'term-main' &
# emacs
emacs -name emacs-main &
setxkbmap us -variant altgr-intl -option ctrl:nocaps &

feh --bg-fill ~/Syncs/Wallpapers/Stones.jpg &
xcompmgr &
#exec xmonad
xrandr --output DVI-D-0 --mode 1280x1024 --primary --output DVI-I-1 --mode 1280x1024 --right-of DVI-D-0 &
